name: vetmanager_url
description: 'Library for getting full vetmanager url by domain name' 
version: 0.0.1
homepage: https://github.com/otis22/vetmanager-url-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
